name: midi_player
description: A Flutter plugin to play midi on iOS and Android uses SoundFont (.sf2) files
version: 0.2.0
homepage: https://github.com/tplkn/midi_player

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: me.teplyakov.midiplayer
        pluginClass: MidiPlayerPlugin
      ios:
        pluginClass: MidiPlayerPlugin
